### PR TITLE
Feature/Use Citation Widget in Preprints [PREP-139]

### PR DESCRIPTION
**Pull request by pattisdr**
❗️ Needs https://github.com/CenterForOpenScience/ember-osf/pull/155
❗️ Needs https://github.com/CenterForOpenScience/osf.io/pull/6623

# Purpose

Drop ember-osf citation widget in content page between Article DOI and Disciplines.

# Ticket

https://openscience.atlassian.net/browse/PREP-139

Old image before changed to preprint citations:
screen shot 2016-11-26 at 6 15 36 pm

With DOI:
screen shot 2016-12-20 at 3 53 27 pm

Without DOI:
screen shot 2016-12-20 at 3 52 21 pm

### CODE REVIEW

**Comment by pattisdr** [comment]
Updating with develop...

**Comment by brianjgeiger** [comment]
Didn't we see that `error Couldn't find package "ember-cli" on the "npm" registry.` last week?

**Comment by binoculars** [comment]
Yes, I believe this is a bug in travis. Pushing a new commit should trigger a new build. I cleared the cache out and re-ran, but the container seems to have network issues.

**Comment by brianjgeiger** [comment]
If you remove the `--prefer-offline` flag @binoculars thinks that should fix the issue.

**Comment by brianjgeiger** [comment]
@pattisdr I cancelled the existing build anticipating the change in the previous comment.

**Comment by pattisdr** [comment]
Do you know why this build might not have started @brianjgeiger? I pushed this change an hour and a half ago.

**Comment by brianjgeiger** [comment]
I don't, but I'll poke at it.

**Comment by abought** [comment]
It's worth noting that Travis limits how many concurrent builds a single user can run at once. I think that limit is applied by organization, not repo- so if there are a lot of PRs in, say, the OSF repo, other projects can find themselves waiting in line.

This seems interesting...
https://blog.travis-ci.com/2014-07-18-per-repository-concurrency-setting/

**Comment by pattisdr** [comment]
I see, thanks @abought. I thought it was per repository.

**Comment by abought** [comment]
> I see, thanks @abought. I thought it was per repository.

One nice thing about the per-organization limit is that you can (sort of) jump the line by [setting your personal repo up to run on travis](https://docs.travis-ci.com/user/getting-started#To-get-started-with-Travis-CI%3A)- the same commit would get run through CI sooner. 

Caveat: if you're not up to date with the COS repo `develop`, then it might not give *quite* the same result (because your personal code may be different from the central repo)- as a result, Travis won't update the status indicator in this PR. But it's a close approximation if you're in a hurry or don't want to run tests locally.

**Pull request merged**
