### PR TITLE
Fix for GUID URL infinite redirects [PREP-300]

### PR DESCRIPTION
**Pull request by binoculars**
## Ticket
https://openscience.atlassian.net/browse/PREP-300

## Notes for reviewers
Create a new preprint, logout, then try to access that url. It should work correctly now.

### CODE REVIEW

**Comment by brianjgeiger** [comment]
@binoculars This has merge conflicts with Master. Can you resolve, please?

**Comment by binoculars** [comment]
Changes resolved. Google Scholar tags were merged and updated in #239

**Comment by brianjgeiger** [comment]
So my intention is to:

1. Revert out Henrique's google scholar stuff from develop with https://github.com/CenterForOpenScience/ember-preprints/pull/246;
2. Merge this;
3. Then some combination of merging back in the google scholar stuff with #239. 

Because I'm not interested in dealing with the merge conflict with this hotfix going into develop. Does that make sense based on what you know?

**Comment by binoculars** [comment]
That should work. If there is a conflict going from master back to develop, I'll resolve it--just let me know. After develop is updated, we can check on #239 and resolve any more conflicts in the PR after that.

**Pull request merged**
