### PR TITLE
Feature/Submit Form Polishing VI

### PR DESCRIPTION
**Pull request by pattisdr**
# Changes
- [x] DOI blank string causing 400 error https://trello.com/c/ZydDgQxI/82-doi-cannot-be-empty-string
- [x] Hitting back button after form submit will reset page https://trello.com/c/M59ttLS6/80-after-creating-a-preprint-and-hitting-the-back-button-the-form-has-not-been-cleared

### CODE REVIEW

**Comment by icereval** [comment]
cherry picked `fbf3b71637461c719a8d4463e1735e16d996ec0b` for the doi fix to get the cards moved around, i'll review the clear/reset next

**Comment by pattisdr** [comment]
I also would like the commits putting resetScrollMixin on all routes.

**Comment by icereval** [comment]
done

**Comment by icereval** [comment]
cherry picked all but reload

**Pull request closed without merging**
