### PR TITLE
[EOSF-488] Add support for Spanish translation

### PR DESCRIPTION
**Pull request by hmoco**
## Ticket

https://openscience.atlassian.net/browse/EOSF-488

## Purpose
Continuation of https://github.com/CenterForOpenScience/ember-preprints/pull/240. With the addition of a test for this and future translations. 

## Side Effects
New items included in translation.js in english will need at least a placeholder translation on every other language.

### CODE REVIEW

**Comment by binoculars** [comment]
Muchas gracias. ¡Esto es increíble!

screen shot 2017-04-13 at 14 43 25

💯

**Comment by hmoco** [comment]
@brianjgeiger, if we do want this feature, the sooner it is merged the better, as tests will begin failing on develop when we merge any PR pointed to develop which includes new terms. This also means that this will require continual upkeep if it doesn't get merged.

**Comment by brianjgeiger** [comment]
@hmoco Only one thing missing. Let's get that fixed and then get this merged in.

**Comment by jamescdavis** [comment]
I went through these kind of quickly and most look pretty good. There are couple that might not have the meaning exactly right and a couple of places where verbs were used when nouns should have been, but I'd say good enough for now.

**Pull request merged**
