### PR TITLE
[hold] Basic citation on content page [PREP-139]

### PR DESCRIPTION
**Pull request by hmoco**
Dependent on https://github.com/CenterForOpenScience/osf.io/pull/6295

### CODE REVIEW

**Comment by caneruguz** [comment]
Waiting on this: https://github.com/CenterForOpenScience/osf.io/pull/6295

**Comment by hmoco** [comment]
@caneruguz, What is the status for merging this? The osf piece seems to have already been merged: https://github.com/CenterForOpenScience/osf.io/pull/6323.

**Comment by caneruguz** [comment]
@icereval you said we are holding this right? I wouldn't add it to develop before we get a clean release branch.

**Comment by binoculars** [comment]
Is this okay to close in favor of CenterForOpenScience/ember-osf#155 and #199 ?

**Comment by hmoco** [comment]
@binoculars yes!

**Pull request closed without merging**
