### PR TITLE
[WIP] Camel case → Kebob case for helper names

### PR DESCRIPTION
**Pull request by binoculars**
## Purpose

Errors from ember-resolver in the latest 2.1.1 update

## Changes

Renaming helpers in the templates

### CODE REVIEW

**Comment by pattisdr** [comment]
Some other helpers needing renaming https://github.com/CenterForOpenScience/ember-preprints/pull/224/commits/44d5b625c392a89137071e1bcdeec65ff69e630b

**Comment by brianjgeiger** [comment]
Based on Dawn's review, this should probably be a hotfix and done soon.

**Comment by icereval** [comment]
Maybe we can cherry pick in the additional changes if others are not ready? This is blocking devs from using docker-compose currently...

**Comment by icereval** [comment]
@pattisdr - for now I've pinned develop to `2.1.0`, in your PR please unpin/upgrade this dependency back to `^2.1.0` as I just wanted to unblock local development for the moment, thanks! 📽

**Pull request closed without merging**
